import { useMemo, useState } from "react";
import { FabricEventStream } from "./shared/components/business/FabricEventStream";
import { JsonBlock } from "./shared/components/business/JsonBlock";
import { PolicyMatrix } from "./shared/components/business/PolicyMatrix";
import { Timeline } from "./shared/components/business/Timeline";
import { SectionCard } from "./shared/components/ui/SectionCard";
import { StatusTag } from "./shared/components/ui/StatusTag";
import { accessTrace, connectors, contract, dataProduct, deliveredV1, fabricEvents, fieldPoliciesV1, fieldPoliciesV2, handshakeSteps } from "./shared/data/mock";
import "./styles/global.css";

type View = "provider" | "consumer" | "audit";
type Tone = "success" | "warning" | "info" | "neutral";
type State = { pr: boolean; cr: boolean; pub: boolean; link: boolean; sync: boolean; req: boolean; ok: boolean; call: boolean };
type Log = { time: string; actor: string; action: string; detail: string; tone: Tone };
const provider = connectors[0], consumer = connectors[1];
const nav: Record<View, [string, string]> = {
  provider: ["Provider 控制台", "身份注册、发布数据集、审批合约、发布字段策略"],
  consumer: ["Consumer 控制台", "注册身份、连接 Provider、同步目录、申请使用、发起调用"],
  audit: ["治理审计台", "身份目录、策略差异、时间摘要与任务日志"],
};
const flow: [keyof State, string][] = [["pr", "Provider 身份"], ["cr", "Consumer 身份"], ["pub", "数据发布"], ["link", "可信连接"], ["sync", "目录同步"], ["req", "申请"], ["ok", "审批"], ["call", "调用"]];

function App() {
  const [active, setActive] = useState<View>("provider");
  const [s, setS] = useState<State>({ pr: true, cr: false, pub: false, link: false, sync: false, req: false, ok: false, call: false });
  const [pv, setPv] = useState<1 | 2>(1);
  const [logs, setLogs] = useState<Log[]>([{ time: "10:00:01", actor: "Provider", action: "ConnectorRegistered", detail: "Provider 身份已写入 DID 目录", tone: "success" }]);
  const policies = pv === 1 ? fieldPoliciesV1 : fieldPoliciesV2;
  const add = (key: keyof State, actor: string, action: string, detail: string, tone: Tone = "success") => {
    setS((old) => ({ ...old, [key]: true }));
    setLogs((old) => [...old, { time: `10:${String(10 + old.length).padStart(2, "0")}:${String(8 + old.length * 4).padStart(2, "0")}`, actor, action, detail, tone }]);
  };
  const publishPolicy = () => { setPv(2); setLogs((old) => [...old, { time: `10:${String(10 + old.length).padStart(2, "0")}:40`, actor: "Provider", action: "PolicyUpdated", detail: "字段策略 v2 发布：phone 从 mask 调整为 deny", tone: "warning" }]); };
  const reset = () => { setS({ pr: true, cr: false, pub: false, link: false, sync: false, req: false, ok: false, call: false }); setPv(1); setLogs((old) => old.slice(0, 1)); };
  const evidence = useMemo(() => ({ contractId: contract.contractId, productId: dataProduct.productId, providerDid: provider.did, consumerDid: consumer.did, status: s.ok ? "active" : s.req ? "pending_provider_approval" : "not_created", policyVersion: pv, contractHash: contract.contractHash, fields: policies.map(({ field, action }) => ({ field, action })) }), [s.ok, s.req, pv, policies]);
  const events = [...fabricEvents, ...logs.slice(1).map((x, i) => ({ eventId: `evt-ui-${i}`, eventType: x.action.includes("Policy") ? "PolicyUpdated" as const : x.action.includes("Delivered") ? "DataDelivered" as const : x.action.includes("Requested") ? "DataAccessRequested" as const : x.action.includes("Contract") ? "ContractSigned" as const : "ProofSubmitted" as const, relatedId: dataProduct.productId, traceId: `trace-ui-${i + 1}`, policyVersion: pv, bodyHash: `sha256:${x.action}`, txHash: `0xui${i + 100}`, timestamp: x.time }))];

  return <div className="shell enterprise-shell"><aside className="sidebar enterprise-sidebar"><div className="brand enterprise-brand"><span>TrustGate-DID</span><strong>DataTrust Platform</strong><small>可交互可信数据连接器运营平台</small></div><div className="side-section-title">工作台视角</div><nav className="workspace-nav">{Object.entries(nav).map(([id, item]) => <button className={active === id ? "active" : ""} key={id} onClick={() => setActive(id as View)}><strong>{item[0]}</strong><span>{item[1]}</span></button>)}</nav><div className="side-health-card"><div><span className="pulse-dot" /><strong>业务流实时联动</strong></div><p>Provider 审批后 Consumer 才能调用，审计台同步身份、策略和日志。</p><button className="ghost-action" onClick={reset}>重置流程</button></div></aside><main className="main enterprise-main"><header className="topbar enterprise-topbar"><div><p>身份注册 → Provider 发布 → Consumer 申请 → Provider 审批 → 调用 → 审计留痕</p><h1>{nav[active][0]}</h1><span>{nav[active][1]}</span></div><div className="topbar__status"><StatusTag tone={s.link ? "success" : "neutral"}>Provider Link</StatusTag><StatusTag tone={s.ok ? "success" : "warning"}>Contract {s.ok ? "Active" : "Pending"}</StatusTag><StatusTag tone="info">Policy v{pv}</StatusTag></div></header><Flow s={s} />{active === "provider" && <Provider s={s} pv={pv} policies={policies} add={add} publishPolicy={publishPolicy} />}{active === "consumer" && <Consumer s={s} pv={pv} policies={policies} add={add} />}{active === "audit" && <Audit s={s} pv={pv} logs={logs} events={events} evidence={evidence} policies={policies} />}</main></div>;
}
function Provider({ s, pv, policies, add, publishPolicy }: { s: State; pv: 1 | 2; policies: typeof fieldPoliciesV1; add: (k: keyof State, a: string, b: string, c: string, d?: Tone) => void; publishPolicy: () => void }) { return <div className="page-grid"><SectionCard title="Provider 身份注册" eyebrow="Identity"><Panel ok={s.pr} title="Provider 入网" text="登记 DID、证书 SAN DID、公钥和服务端点。" action="注册/更新身份" onClick={() => add("pr", "Provider", "ConnectorRegistered", "Provider DID 与证书绑定完成")} /></SectionCard><SectionCard title="发布数据集" eyebrow="Dataset" className="wide"><div className="upload-console"><div className="dropzone"><span>CSV / Parquet / API</span><strong>order_transaction_2026_sample.csv</strong><p>发布后 Consumer 才能同步目录并申请。</p><button className="primary-action" disabled={!s.pr || s.pub} onClick={() => add("pub", "Provider", "DatasetPublished", "数据集已发布到 Provider 目录")}>{s.pub ? "已发布" : "发布数据集"}</button></div><PolicyMatrix fields={dataProduct.schema} policies={policies} /></div></SectionCard><SectionCard title="字段策略" eyebrow="Policy"><div className="api-card"><strong>当前策略：v{pv}</strong><p>v2 会把 phone 从 mask 改为 deny。</p><button className="primary-action" disabled={pv === 2} onClick={publishPolicy}>发布字段策略 v2</button></div></SectionCard><SectionCard title="审批合约" eyebrow="Approval"><div className="approval-card"><StatusTag tone={s.req ? s.ok ? "success" : "warning" : "neutral"}>{s.req ? s.ok ? "已接受" : "待审批" : "暂无请求"}</StatusTag><h3>{consumer.connectorId}</h3><p>申请产品：{dataProduct.name}；用途：risk_analysis。</p><button className="primary-action" disabled={!s.req || s.ok} onClick={() => add("ok", "Provider", "ContractSigned", "已接受 Consumer 请求并生成合约")}>{s.ok ? "合约已生效" : "接受请求并生成合约"}</button></div></SectionCard><SectionCard title="数据产品状态" eyebrow="Runtime" className="wide"><StateTable s={s} pv={pv} /></SectionCard></div>; }
function Consumer({ s, pv, policies, add }: { s: State; pv: 1 | 2; policies: typeof fieldPoliciesV1; add: (k: keyof State, a: string, b: string, c: string, d?: Tone) => void }) { return <div className="page-grid"><SectionCard title="Consumer 身份注册" eyebrow="Identity"><Panel ok={s.cr} title="Consumer 入网" text="注册 Consumer DID、证书和回调端点。" action="注册 Consumer 身份" onClick={() => add("cr", "Consumer", "ConnectorRegistered", "Consumer DID 与证书已登记")} /></SectionCard><SectionCard title="连接 Provider" eyebrow="Link"><Action disabled={!s.cr || s.link} done={s.link} label="建立 DID-mTLS 连接" doneLabel="已连接" onClick={() => add("link", "Consumer", "ProviderConnected", "DID-mTLS 握手完成，可信连接建立")} /></SectionCard><SectionCard title="同步目录" eyebrow="Catalog" className="wide"><Action disabled={!s.link || !s.pub || s.sync} done={s.sync} label="同步目录" doneLabel="目录已同步" onClick={() => add("sync", "Consumer", "CatalogSynced", "已同步 Provider 数据目录")} /><StateTable s={s} pv={pv} /></SectionCard><SectionCard title="申请使用" eyebrow="Request"><Action disabled={!s.sync || s.req} done={s.req} label="提交使用申请" doneLabel="申请已提交" onClick={() => add("req", "Consumer", "DataAccessRequested", "已提交 risk_analysis 使用申请", "info")} /></SectionCard><SectionCard title="发起数据调用" eyebrow="Invocation"><Action disabled={!s.ok} done={s.call} label="发起数据调用" doneLabel="再次调用" onClick={() => add("call", "Consumer", "DataDelivered", "数据调用成功，返回字段级受控结果")} /></SectionCard><SectionCard title="调用结果" eyebrow="Result" className="wide"><div className="json-grid"><JsonBlock title="请求参数" value={{ productId: dataProduct.productId, purpose: contract.purpose, policyVersion: pv, consumerDid: consumer.did }} /><JsonBlock title={s.call ? "受控返回" : "等待审批/调用"} value={s.call ? deliveredV1 : { status: s.ok ? "ready_to_invoke" : "blocked" }} /></div>{s.call ? <PolicyMatrix fields={dataProduct.schema} policies={policies} /> : null}</SectionCard></div>; }
function Audit({ s, pv, logs, events, evidence, policies }: { s: State; pv: 1 | 2; logs: Log[]; events: typeof fabricEvents; evidence: object; policies: typeof fieldPoliciesV1 }) { return <div className="page-grid"><SectionCard title="身份目录" eyebrow="Directory" className="wide"><div className="identity-directory"><Id name="Provider" did={provider.did} ok={s.pr} /><Id name="Consumer" did={consumer.did} ok={s.cr} /></div></SectionCard><SectionCard title="策略差异" eyebrow="Diff" className="wide"><div className="policy-diff"><PolicyMatrix fields={dataProduct.schema} policies={fieldPoliciesV1} /><PolicyMatrix fields={dataProduct.schema} policies={fieldPoliciesV2} /></div><p className="notice">当前生效策略：v{pv}，共 {policies.length} 个字段策略。</p></SectionCard><SectionCard title="时间摘要 / 任务日志" eyebrow="Task Log" className="wide"><div className="task-log">{logs.map((x, i) => <div key={i}><span>{x.time}</span><strong>{x.actor} · {x.action}</strong><p>{x.detail}</p><StatusTag tone={x.tone}>{x.tone}</StatusTag></div>)}</div></SectionCard><SectionCard title="Fabric 事件" eyebrow="On-chain"><FabricEventStream events={events} /></SectionCard><SectionCard title="合约证据" eyebrow="Evidence"><JsonBlock title="合约摘要" value={evidence} /></SectionCard><SectionCard title="访问追踪" eyebrow="Trace" className="wide"><div className="trace-console"><Timeline steps={s.call ? accessTrace.steps : handshakeSteps} /><dl className="kv-list compact trace-meta"><div><dt>traceId</dt><dd>{s.call ? "trace-ui-call-001" : "等待调用"}</dd></div><div><dt>responseHash</dt><dd>{s.call ? accessTrace.responseHash : "-"}</dd></div></dl></div></SectionCard></div>; }
function Flow({ s }: { s: State }) { return <div className="flow-strip">{flow.map(([k, n]) => <div className={s[k] ? "done" : ""} key={k}><span>{s[k] ? "✓" : "·"}</span>{n}</div>)}</div>; }
function Panel(p: { ok: boolean; title: string; text: string; action: string; onClick: () => void }) { return <div className="ops-panel"><StatusTag tone={p.ok ? "success" : "warning"}>{p.ok ? "已注册" : "待注册"}</StatusTag><h3>{p.title}</h3><p>{p.text}</p><button className="primary-action" disabled={p.ok} onClick={p.onClick}>{p.ok ? "身份已注册" : p.action}</button></div>; }
function Action(p: { disabled: boolean; done: boolean; label: string; doneLabel: string; onClick: () => void }) { return <div className="api-card"><button className="primary-action" disabled={p.disabled} onClick={p.onClick}>{p.done ? p.doneLabel : p.label}</button></div>; }
function StateTable({ s, pv }: { s: State; pv: 1 | 2 }) { return <div className="table-wrap enterprise-table"><table><tbody><tr><td><strong>{dataProduct.name}</strong><small>{dataProduct.productId}</small></td><td><StatusTag tone={s.pub ? "success" : "neutral"}>{s.pub ? "已发布" : "待发布"}</StatusTag></td><td>field-level-v{pv}</td><td>{s.ok ? "active" : s.req ? "待审批" : "等待客户请求"}</td></tr></tbody></table></div>; }
function Id({ name, did, ok }: { name: string; did: string; ok: boolean }) { return <div className="identity-row"><div><strong>{name}</strong><span>{did}</span></div><StatusTag tone={ok ? "success" : "warning"}>{ok ? "active" : "not registered"}</StatusTag></div>; }
export default App;
